<?php
/**
 * @file
 * PR Requests Module for Drupal 7.x.
 *
 * This module handles submission requests to the Fredericton UNB Libraries' PR
 * Group. It provides a request form and configurable PR Group email list.
 * Corresponding FogBugz ticket is created, applicant is sent a confirmation
 * email and members of the email list are notified upon successful request
 * submissions.
 */

?>

<?php
/**
 * Implements PR Requests hook_menu().
 */
function pr_requests_menu() {
  $items = array();

  $items['pr-requests'] = array(
    'title' => 'PR Requests',
    'description' => 'A form used to request PR Group assistance.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pr_requests_form'),
    'file' => 'forms/pr_requests_form.inc.php',
    'access arguments' => array('submit pr requests'),
  );

  $items['admin/config/pr-requests'] = array(
    'title' => 'PR Requests settings',
    'description' => 'Configure PR Group email list and file upload options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pr_requests_settings_form'),
    'file' => 'forms/pr_requests_settings_form.inc.php',
    'access callback' => '_pr_requests_settings_form_access',
  );

  return $items;
}

/**
 * Add PR Requests category settings to People|Permissions.
 */
function pr_requests_permission() {
  return array(
    'submit pr requests' => array(
      'title' => t('Submit PR Requests'),
    ),
    'admin pr requests' => array(
      'title' => t('Administer PR Requests Settings'),
    ),
  );
}

/**
 * Implements PR Requests settings form access permissions.
 */
function _pr_requests_settings_form_access() {
  if (user_access('admin pr requests') || user_access('administer site configuration')) {
    return TRUE;
  }
  return FALSE;
}
