<?php
/**
 * @file
 * PR Requests Module for Drupal 7.x.
 *
 * This module handles submission requests to the Fredericton UNB Libraries' PR
 * Group. It provides a request form and configurable PR Group email list.
 * Corresponding FogBugz ticket is created, applicant is sent a confirmation
 * email and members of the email list are notified upon successful request
 * submissions.
 */

?>

<?php
/**
 * Implements PR Requests hook_menu().
 */
function pr_requests_menu() {
  $items = array();

  $items['pr-requests'] = array(
    'title' => 'PR Requests',
    'description' => 'A form used to request PR Group assistance.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pr_requests_form'),
    'access arguments' => array('submit pr requests'),
  );

  $items['admin/config/pr-requests'] = array(
    'title' => 'PR Requests settings',
    'description' => 'Configure PR Group email list and file upload options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('pr_requests_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Add People|Permissions row entry + Modules "Permissions" link.
 */
function pr_requests_permission() {
  return array(
    'submit pr requests' => array(
      'title' => t('Submit PR Requests'),
    ),
  );
}

/**
 * Handler for PR Requests settings.
 *
 * Set e-mail list, max file uploads, accepted fiel extensions, max file size.
 */
function pr_requests_settings($form, &$form_state) {
  drupal_set_title('PR Group request form settings');
  $form['pr_requests_email_list'] = array(
    '#type' => 'textarea',
    '#title' => t('PR Group email list:'),
    '#default_value' => variable_get('pr_requests_email_list', ''),
    '#description' => t('Enter a valid email address. Separate multiple
      with a comma'),
  );

  /* File upload settings group */
  $form['file_uploads'] = array(
    '#type' => 'fieldset',
    '#title' => t('File upload settings:'),
  );

  $form['file_uploads']['pr_requests_files_limit'] = array(
    '#type' => 'numberfield',
    '#title' => t('Maximum allowable file uploads:'),
    '#description' => t('Enter an upper limit of file attachments'),
    '#default_value' => variable_get('pr_requests_files_limit', 3),
    '#element_validate' => array('element_validate_integer_positive'),
    '#maxlength' => 2,
    '#attributes' => array(
      'min' => 1,
      'max' => 12,
    ),
  );

  $form['file_uploads']['pr_requests_file_extensions'] = array(
    '#type' => 'textfield',
    '#title' => t('Valid file upload types:'),
    '#default_value' => variable_get('pr_requests_file_extensions', 'gif jpg png doc docx pdf zip'),
    '#description' => t('Restrict accepted file extensions, i.e. gif jpg png doc docx pdf zip'),
  );

  $my_max_fsize = file_upload_max_size() / 1024 / 1024;
  $form['file_uploads']['pr_requests_file_maxsize'] = array(
    '#type' => 'numberfield',
    '#title' => t('Maximum allowable file upload size:'),
    '#description' => t('Enter a numeric file size between <b>1</b> and
      <b>%limit</b>', array('%limit' => format_size(file_upload_max_size()))
    ),
    '#default_value' => variable_get('pr_requests_file_maxsize', $my_max_fsize),
    '#element_validate' => array('element_validate_integer_positive'),
    '#maxlength' => 3,
    '#attributes' => array(
      'min' => 1,
      'max' => $my_max_fsize,
    ),
  );

  /* FogBugz credentials group */
  $form['fogbugz_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Fogbugz credentials:'),
  );

  $form['fogbugz_settings']['pr_requests_fogbugz_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#default_value' => variable_get('pr_requests_fogbugz_email'),
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
    '#prefix' => '<p>Enter the credentials for the FogBugz account that will be used for API calls in this module.</p>',
  );

  $form['fogbugz_settings']['pr_requests_fogbugz_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#default_value' => variable_get('pr_requests_fogbugz_password'),
    '#size' => 50,
    '#maxlength' => 50,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook__settings_permission().
 */
function pr_requests_settings_permission() {
  return array(
    'access pr requests' => array(
      'title' => t('Administer PR Requests'),
    ),
  );
}

/**
 * Implements PR Requests form creation.
 */
function pr_requests_form($form, &$form_state) {
  drupal_set_title('PR Group Assistance Request');
  $form['supervisor_approved'] = array(
    '#type' => 'checkbox',
    '#title' => t('Unit manager is aware of and supports this request.'),
    '#prefix' => '<p class="instructions">To request assistance from the PR
      group, please complete and submit this form. A confirmation email will be
      sent upon receipt. If there are any follow up questions, or if consultation
      is required, you will be notified. Please note that requests will be
      prioritized. Once the request is approved, the appropriate individuals on
      the PR Committee will complete the tasks involved by the agreed-upon date.
      </p>',
    '#required' => TRUE,
  );

  $form['conditional-wrapper'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'class' => array(
        'pr-request-form-toggle',
      ),
    ),
    '#states' => array(
      'visible' => array(
        ':input[name="supervisor_approved"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['conditional-wrapper']['project'] = array(
    '#type' => 'fieldset',
    '#title' => t('Project Information:'),
  );

  $form['conditional-wrapper']['project']['deadline'] = array(
    '#type' => 'date_popup',
    '#title' => t('Deadline'),
    '#required' => TRUE,
    '#date_format' => 'Y-m-d',
  );

  $form['conditional-wrapper']['project']['category'] = array(
    '#type' => 'select',
    '#title' => t('PR Category'),
    '#options' => array(
      'announcement' => t('Announcement'),
      'event' => t('Event (General)'),
      'teaching' => t('Teaching Session/Workshop'),
      'eresource' => t('e-Resource'),
      'services' => t('Services'),
      'spaces' => t('Physical Spaces'),
      'other' => t('Other'),
    ),
    '#required' => TRUE,
  );

  $form['conditional-wrapper']['project']['other'] = array(
    '#type' => 'textfield',
    '#title' => t('Please specify other category:'),
    '#states' => array(
      'visible' => array(
        ':input[name="category"]' => array('value' => 'other'),
      ),
      'required' => array(
        ':input[name="category"]' => array('value' => 'other'),
      ),
    ),
  );

  $form['conditional-wrapper']['project']['about'] = array(
    '#type' => 'textarea',
    '#title' => 'About the Project',
    '#description' => 'Please provide any vital information concerning your
      request. i.e. Dates, times, locations, product information, etc.',
    '#required' => TRUE,
  );

  $form['conditional-wrapper']['project']['content'] = array(
    '#type' => 'textarea',
    '#title' => t('Content'),
    '#description' => t('Content to be included with the PR Request. i.e.
      information/images to include in Library News article, Library Feature,
      Social Media Posts, etc.'),
    '#required' => TRUE,
  );

  $form['conditional-wrapper']['project']['target'] = array(
    '#type' => 'textarea',
    '#title' => t('Target Audience'),
    '#description' => t('i.e. Faculty, students, general public, UNB/STU,
      etc.'),
    '#required' => TRUE,
  );

  $my_file_limit = variable_get('pr_requests_files_limit');
  $my_file_extensions = variable_get('pr_requests_file_extensions');
  $my_file_maxsize = variable_get('pr_requests_file_maxsize');

  $form['conditional-wrapper']['files'] = array(
    '#type' => 'fieldset',
    '#title' => t('Files'),
    '#description' => t('<p>You may upload up to %my_file_limit files to
      accompany your request. If you have more than %my_file_limitfiles,
      you may upload a .zip file instead.<br />Permitted file extensions
      include: <b>%my_file_extensions</b></p><p><b>Note:</b> the maximum file
      size is %my_file_max_sizeMB</p>', array(
        '%my_file_limit' => $my_file_limit,
        '%my_file_extensions' => $my_file_extensions,
        '%my_file_max_size' => $my_file_maxsize,
      )
    ),
  );

  $form['conditional-wrapper']['files']['file_input_container'] = array(
    '#type' => 'container',
    '#title' => 'File Input Container',
    '#attributes' => array(
      'id' => array(
        'pr-requests-files-wrapper',
      ),
    ),
  );

  // Form widgets for public file uploads.
  for ($i = 1; $i <= $my_file_limit; $i++) {
    $form['conditional-wrapper']['files']['file_input_container']['file' . $i] = array(
      '#title' => 'File' . $i,
      '#title_display' => 'invisible',
      '#type' => 'managed_file',
      '#upload_location' => 'public://pr_requests/',
      '#upload_validators' => array(
        'file_validate_extensions' => array(
          'gif jpg png doc docx pdf zip',
        ),
        'file_validate_size' => array(
          $my_file_maxsize * 1024 * 1024,
        ),
      ),
    );
  }

  $form['conditional-wrapper']['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Send request'),
    '#attributes' => array(
      'class' => array(
        'pr-requests-send-button',
      ),
    ),
    '#submit' => array(
      '_pr_requests_submit',
    ),
  );

  return $form;
}

/**
 * Implements PR Requests form submission handler.
 */
function pr_requests_form_submit($form, &$form_state) {
  $token = _pr_requests_get_fogbugz_token();
  if ($token == NULL) {
    drupal_set_message(t('Connection to FogBugz failed. If this error persists, please contact the site administrator.'), 'error');
    return;
  }
  $success = _pr_requests_create_fogbugz_ticket($token, $form_state);
  if ($success) {
    drupal_set_message(t('Your request has been submitted to the PR Group. We will send you a confirmation email shortly.'));
  }
  else {
    drupal_set_message(t('Your submission request was not successful. If this error persists, please contact the site administrator.'), 'error');
  }
}

/**
 * Generate and return FogBugz token.
 *
 * Authenticates Mr. Robot through the FogBugz API and generates a token for
 * subsequent API calls.
 *
 * @return string
 *   Token for FogBugz API calls
 */
function _pr_requests_get_fogbugz_token() {
  $curl_handle = curl_init('https://support.lib.unb.ca/api.asp?cmd=logon');

  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($curl_handle, CURLOPT_POST, TRUE);
  $ch_post_data = array(
    'email' => variable_get('pr_requests_fogbugz_email'),
    'password' => variable_get('pr_requests_fogbugz_password'),
  );
  curl_setopt($curl_handle, CURLOPT_POSTFIELDS, $ch_post_data);

  $curl_response = curl_exec($curl_handle);
  $token = NULL;
  if ($curl_response) {
    $xml = simplexml_load_string($curl_response, 'SimpleXMLElement', LIBXML_NOCDATA);
    $token = (string) $xml->token;
  }
  curl_close($curl_handle);

  return $token;
}

/**
 * Create a ticket in FogBugz system based on user input from the ticket form.
 *
 * @param string $token
 *   Token for FogBugz API calls.
 * @param array $form_state
 *   Form state.
 *
 * @return bool
 *   TRUE if ticket creation successfully returned a case ID, FALSE if not
 */
function _pr_requests_create_fogbugz_ticket($token, array $form_state) {
  $description = "Contact Information:\n" .
                $form_state['values']['name'] . "\n" .
                $form_state['values']['department'] . "\n" .
                $form_state['values']['email'] . "\n" .
                $form_state['values']['phone'] . "\n\nDeadline:\n" .
                $form_state['values']['deadline'] . "\n\nAbout the project:\n" .
                $form_state['values']['about'] . "\n\nGraphic material request:\n" .
                $form_state['values']['graphic_material'] . "\n\nContent:\n" .
                $form_state['values']['content'] . "\n\nTarget Audience:\n" .
                $form_state['values']['target'] . "\n\n";

  $ticket_information = array(
    'project' => 'PR Requests',
    'title' => 'PR Request from ' . $form_state['values']['name'],
    'category' => 'PR Request',
    'description' => $description,
    'email' => $form_state['values']['name'] . "<" . $form_state['values']['email'] . ">",
  );

  $curl_handle = curl_init('https://support.lib.unb.ca/api.asp?cmd=new');
  curl_setopt($curl_handle, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($curl_handle, CURLOPT_POST, TRUE);
  curl_setopt($curl_handle, CURLOPT_HTTPHEADER, array("Content-Type:multipart/form-data"));
  $ch_post_data = array(
    'token' => $token,
    'sProject' => $ticket_information['project'],
    'sTitle' => $ticket_information['title'],
    'sCategory' => $ticket_information['category'],
    'sEvent' => $ticket_information['description'],
    'sCustomerEmail' => $ticket_information['email'],
    'ixMailbox' => 1,
  );

  $file_count = 0;
  foreach ($form_state['values'] as $field_name => $fid) {
    if (preg_match('/(file)\d/', $field_name) > 0 && $fid > 0) {
      $file_count++;
      $file = file_load($fid);
      $file_uri = drupal_realpath($file->uri);
      $ch_post_data['File' . $file_count] = new CurlFile($file_uri);
    }
  }
  $ch_post_data['nFileCount'] = $file_count;

  curl_setopt($curl_handle, CURLOPT_POSTFIELDS, $ch_post_data);

  // Makes actual connection to FogBugz
  // $curl_response = curl_exec($curl_handle);
  $success = FALSE;
  $case_id = NULL;
  if ($curl_response) {
    $xml = simplexml_load_string($curl_response, 'SimpleXMLElement', LIBXML_NOCDATA);
    $case_id = (string) $xml->case['ixBug'];
    if ($case_id != NULL) {
      $ticket_information['case_id'] = $case_id;
      $success = TRUE;
      _pr_requests_send_confirmation_email($token, $ticket_information);
    }
  }
  // curl_close($curl_handle);
  return $success;

}

/**
 * Implements PR Requests form validation.
 */
function pr_requests_form_validate($form, &$form_state) {
  $mail = $form_state['values']['email'];
  if (!valid_email_address($mail)) {
    form_set_error('email', t('Please Enter a valid email address.'));
  }
  var_dump($form_state['values']);

  return $form;
}
